name: Policy Framework KinD tests

on:
  pull_request:
    branches:
      - main
      - release-2.[7-9]

jobs:
  fw-kind-tests:
    name: Config FW KinD Tests
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@reusable-kind-workflow
