name: KinD tests

on:
  pull_request:
    branches:
      - main
      - release-2.[4-9] # only framework 2.4+ might have the right make targets

defaults:
  run:
    shell: bash

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    strategy:
      matrix:
        go:
          - '1.17'
        # Run tests on oldest and newest supported OCP Kubernetes
        # - OCP 4.5 runs Kubernetes v1.18
        # KinD tags: https://hub.docker.com/r/kindest/node/tags
        kind:
          - 'v1.18.15'
          # - 'latest'
        deployOnHub:
          - 'true'
          - 'false'

    name: Policy Framework KinD tests
    steps:
    - name: Checkout Config Policy Controller
      uses: actions/checkout@v2
      with:
        path: config-policy-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Checkout Policy Framework
      uses: actions/checkout@v2
      with:
        path: governance-policy-framework
        repository: stolostron/governance-policy-framework
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Set up Go - ${{ matrix.go }}
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Policy Framework cluster bootstrap
      working-directory: governance-policy-framework
      env:
        deployOnHub: ${{ matrix.deployOnHub }}
      run: |
        make e2e-dependencies
        make kind-bootstrap-cluster

        echo "* Listing all pods on cluster..."
        kubectl get pods -A

        echo "MANAGED_KUBECONFIG=$(pwd)/kubeconfig_managed" >> $GITHUB_ENV
        echo "HUB_KUBECONFIG=$(pwd)/kubeconfig_hub" >> $GITHUB_ENV

    - name: Patch image
      working-directory: config-policy-controller
      env:
        deployOnHub: ${{ matrix.deployOnHub }}
        WATCH_NAMESPACE: managed
      run: |
        export KUBECONFIG=${MANAGED_KUBECONFIG}
        if [[ "${deployOnHub}" == "true" ]]; then
          export KIND_NAME=hub
        else
          export KIND_NAME=managed
        fi

        make build-images
        make kind-deploy-controller-dev

    - name: Policy Framework e2e tests
      working-directory: governance-policy-framework
      run: |
        make e2e-test

    - name: Debug
      if: ${{ failure() }}
      working-directory: governance-policy-framework
      run: |
        make e2e-debug
